male(anna).
male(chandu).
male(ganesh).
male(pinto).
male(ajey).
male(pradeep).
male(vijay).
male(kishor).
male(sankalp).
male(shubham).
male(sahil).
male(nilesh).
male(sai).


female(lata).
female(surekha).
female(asha).
female(aditi).
female(bai).
female(shweta).
female(jyoti).
female(karishma).
female(shrishti).
female(nidhi).
female(mrunali).
female(rutu).
female(surbhi).

parent(anna,chandu).
parent(anna,asha).
parent(lata,chandu).
parent(lata,ganesh).
parent(surekha,pinto).
parent(surekha,bai).
parent(surekha,nilesh).
parent(chandu,pinto).
parent(chandu,bai).
parent(chandu,nilesh).
parent(bai,sai).
parent(ajey,sai).
parent(ganesh,pradeep).
parent(ganesh,jyoti).
parent(ganesh,karishma).
parent(asha,pradeep).
parent(asha,jyoti).
parent(asha,karishma).
parent(shweta,shrishti).
parent(shweta,sankalp).
parent(pradeep,shrishti).
parent(pradeep,sankalp).
parent(jyoti,nidhi).
parent(jyoti,shubham).
parent(vijay,nidhi).
parent(vijay,shubham).
parent(karishma,sahil).
parent(karishma,mrunali).
parent(kishor,sahil).
parent(kishor,mrunali).
parent(nilesh,surbhi).
parent(rutu,surbhi).

wife(lata,anna).
wife(surekha,chandu).
wife(asha,ganesh).
wife(aditi,pinto).
wife(bai,ajey).
wife(shweta,pradeep).
wife(jyoti,vijay).
wife(karishma,kishor).
wife(rutu,nilesh).

mother(X,Y):-female(X),parent(X,Y).
father(X,Y):-male(X),parent(X,Y).
sibling(X,Y) :-parent(Z,X),parent(Z,Y),X\=Y.
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandfather(X,Y):-male(X),parent(X,Z),parent(Z,Y).
grandmother(X,Y):-female(X),parent(X,Z),parent(Z,Y).
secondgrandfather(X,Y):-male(X),sibling(X,Z),grandparent(Z,Y);male(X),wife(A,X),sibling(B,A),grandparent(B,Y).
secondgrandmother(X,Y):-female(X),sibling(X,Z),grandparent(Z,Y);female(X),wife(X,A),sibling(A,B),grandparent(B,Y).
maternal_aunt(X,Y):-female(X),sibling(X,A),mother(A,Y);female(X),wife(X,A),sibling(A,B),parent(B,Y).
maternal_uncle(X,Y):-male(X),sibling(X,A),mother(A,Y);male(X),wife(A,X),sibling(A,B),parent(B,Y).
cousin(X,Y):-parent(A,Y),sibling(A,B),parent(B,X).
secondcousin(X,Y):-parent(A,Y),cousin(A,B),parent(B,X).
second_maternal_uncle(X,Y):-male(X),mother(A,Y),cousin(A,X);male(X),parent(A,Y),cousin(A,B),wife(B,X).
second_maternal_aunt(X,Y):-female(X),mother(A,Y),cousin(A,X);female(X),parent(A,Y),cousin(A,B),wife(X,B).
paternal_aunt(X,Y):-female(X),father(A,Y),sibling(X,A);female(X),father(A,Y),sibling(B,A),wife(X,B).
paternal_uncle(X,Y):-male(X),father(A,Y),sibling(A,X);male(X),father(A,Y),sibling(B,A),wife(B,X).
second_paternal_aunt(X,Y):-female(X),father(A,Y),cousin(A,X);female(X),father(A,Y),cousin(A,B),wife(X,B).
second_paternal_uncle(X,Y):-male(X),father(A,Y),cousin(A,X);male(X),father(A,Y),cousin(A,B),wife(B,X).
daughter_in_law(X,Y):-female(X),parent(Y,A),wife(X,A).
son_in_law(X,Y):-male(X),parent(Y,A),wife(A,X).
uncle_in_law(X,Y):-male(X),female(Y),wife(Y,A),paternal_uncle(X,A),male(X);male(X),female(Y),wife(Y,A),maternal_uncle(X,A);male(X),male(Y),wife(A,Y),paternal_uncle(X,A);male(X),male(Y),wife(A,Y),maternal_uncle(X,A).
aunt_in_law(X,Y):-uncle_in_law(A,Y),wife(X,A).
sister_in_law(X,Y):-female(X),wife(X,A),sibling(A,Y);female(X),wife(X,A),cousin(A,Y);wife(X,A),sibling(A,B),wife(B,Y).
brother_in_law(X,Y):-male(X),wife(A,X),sibling(A,Y);male(X),wife(A,X),cousin(A,Y).
greatgrandparent(X,Y):-grandparent(A,Y),parent(X,A).
husbands_cousins_wife(X,Y):-female(X),wife(X,A),cousin(A,B),wife(Y,B).
wifes_sister_in_law(X,Y):-female(X),wife(A,Y),sister_in_law(X,A).
